name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # DEBUG (taruh di dalam steps)
      - name: Debug FTP Server
        run: echo "Server is ${{ secrets.FTP_SERVER }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Vite
        run: |
          npm install
          npm run build

      - name: Deploy Core
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /domains/eggtraycpl.com/compro-ptcpl/
          exclude: |
            **/.git*
            **/.env
            **/node_modules/**
            public/**
            storage/**

      - name: Deploy Public
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /domains/eggtraycpl.com/public_html/