name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Vite
        run: |
          npm install
          npm run build

      # 🚀 DEPLOY CORE (Laravel)
      - name: Deploy Core via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 65002
          source: "."
          target: "/home/u991429839/domains/eggtraycpl.com/compro-ptcpl"
          rm: false

      # 🚀 DEPLOY PUBLIC (assets + index.php)
      - name: Deploy Public via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 65002
          source: "public"
          target: "/home/u991429839/domains/eggtraycpl.com/public_html"
          strip_components: 1
          rm: true

          